### ISSUE TITLE
Color story is not rendering

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/ui#66]
It seems like something is wrong with the Storybook/webpack/postcss config since the imported colors.css

https://github.com/freeCodeCamp/ui/blob/3f53bf366e4e4e0389a9f6bec447e62c48340aeb/src/color-system/color-system.tsx#L3

is undefined, leading to the following errors.

Production:

```
ReferenceError: Cannot access 'color_system_stories' before initialization
    at Module.default (https://opensource.freecodecamp.org/ui/color-system-color-system-stories.c183092e.iframe.bundle.js:1:385)
    at processCSFFile (https://opensource.freecodecamp.org/ui/sb-preview/runtime.js:100:1907)
    at StoryStore.memoizerific [as processCSFFileWithCache] (https://opensource.freecodecamp.org/ui/sb-preview/runtime.js:1:4751)
    at CsfDocsRender.prepare (https://opensource.freecodecamp.org/ui/sb-preview/runtime.js:121:900)
    at async PreviewWeb.renderSelection (https://opensource.freecodecamp.org/ui/sb-preview/runtime.js:121:9522)
```

Development:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ./src/color-system/color-system.tsx (http://localhost:6006/color-system-color-system-stories.iframe.bundle.js:62:37)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:323:21)
    at ./src/color-system/color-system.stories.tsx (http://localhost:6006/color-system-color-system-stories.iframe.bundle.js:17:71)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:323:21)
    at http://localhost:6006/main.iframe.bundle.js:2839:10
    at async StoryStore.importFn (http://localhost:6006/main.iframe.bundle.js:92:27)
    at async Promise.all (index 0)
```

https://opensource.freecodecamp.org/ui/?path=/docs/design-system-color--docs

**Comment by ojeytonwilliams** [comment]
I'm not sure, to be honest. I spent a fair bit of time on this and it was far from obvious.

That said, it's fairly clear that a bundler will be necessary.

> revisit our tooling as I don't think it would make sense to use both webpack and rollup.

Agreed. I suspect moving to webpack is the way to go, but I'm not sure.
